import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from 'next-themes';
import { NextAuthProvider } from '~/components/app-shell/NextAuthProvider';
import { SWRProvider } from '~/components/app-shell/SWRProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400;600&display=swap&subset=latin"
          rel="stylesheet"
        />
      </head>

      <body>
        <ThemeProvider attribute="class" defaultTheme="light">
          <SWRProvider>
            <NextAuthProvider>{children}</NextAuthProvider>
          </SWRProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
